spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soutenance_bd
    username: root
    password:
  jpa:
    defer-datasource-initialization: true

    show-sql: true
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
